data:
  name: iris_v1
features:
  version: iris_v1_features_v1
model:
  name: decision_tree
  params:
    max_depth: 3
experiment:
  name: Iris Classification Experiments
  mode: train # or replay
  runId: pass # not needed for train
